import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SearchBar from "@/components/SearchBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative bg-black">
          <div className="absolute h-full w-full top-0 left-0">
            <img
              src="/background.png"
              alt="background-image"
              className="h-screen w-full object-cover"
            />
          </div>
          <div className="absolute h-screen w-full top-0 left-0 bg-gradient-to-b from-black/10 to-black"></div>
          <div className="relative">
            <SearchBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
